blank_issues_enabled: true
contact_links:
  - name: Contributing guidelines
    url: https://github.com/bosun-monitor/bosun-grafana-app/blob/master/CONTRIBUTING.md
    about: Please read the contributing guidelines for this project.
  - name: Code Of Conduct
    url: https://github.com/bosun-monitor/bosun-grafana-app/blob/master/CODE_OF_CONDUCT.md
    about: This space is protected by our code of conduct.
